//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExclusiveCakesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public Nullable<int> PieID { get; set; }
        public Nullable<int> CompositionID { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<int> FormID { get; set; }
        public string Inscription { get; set; }
        public byte[] Image { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GettingID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Branches Branches { get; set; }
        public virtual Compositions Compositions { get; set; }
        public virtual Forms Forms { get; set; }
        public virtual GettinTypes GettinTypes { get; set; }
        public virtual PieCatalogs PieCatalogs { get; set; }
        public virtual Statements Statements { get; set; }
    }
}
